//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyncAxis2Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://axis2server.services.com", ConfigurationName="ServiceReference1.TextFileContentRetrieverPortType")]
    public interface TextFileContentRetrieverPortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:test", ReplyAction="urn:testResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AsyncAxis2Client.ServiceReference1.testResponse test(AsyncAxis2Client.ServiceReference1.testRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:test", ReplyAction="urn:testResponse")]
        System.Threading.Tasks.Task<AsyncAxis2Client.ServiceReference1.testResponse> testAsync(AsyncAxis2Client.ServiceReference1.testRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:retrieveTextFileContent", ReplyAction="urn:retrieveTextFileContentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AsyncAxis2Client.ServiceReference1.retrieveTextFileContentResponse retrieveTextFileContent(AsyncAxis2Client.ServiceReference1.retrieveTextFileContentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:retrieveTextFileContent", ReplyAction="urn:retrieveTextFileContentResponse")]
        System.Threading.Tasks.Task<AsyncAxis2Client.ServiceReference1.retrieveTextFileContentResponse> retrieveTextFileContentAsync(AsyncAxis2Client.ServiceReference1.retrieveTextFileContentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="test", WrapperNamespace="http://axis2server.services.com", IsWrapped=true)]
    public partial class testRequest {
        
        public testRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="testResponse", WrapperNamespace="http://axis2server.services.com", IsWrapped=true)]
    public partial class testResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://axis2server.services.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public testResponse() {
        }
        
        public testResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveTextFileContent", WrapperNamespace="http://axis2server.services.com", IsWrapped=true)]
    public partial class retrieveTextFileContentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://axis2server.services.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string path;
        
        public retrieveTextFileContentRequest() {
        }
        
        public retrieveTextFileContentRequest(string path) {
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveTextFileContentResponse", WrapperNamespace="http://axis2server.services.com", IsWrapped=true)]
    public partial class retrieveTextFileContentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://axis2server.services.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public retrieveTextFileContentResponse() {
        }
        
        public retrieveTextFileContentResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TextFileContentRetrieverPortTypeChannel : AsyncAxis2Client.ServiceReference1.TextFileContentRetrieverPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TextFileContentRetrieverPortTypeClient : System.ServiceModel.ClientBase<AsyncAxis2Client.ServiceReference1.TextFileContentRetrieverPortType>, AsyncAxis2Client.ServiceReference1.TextFileContentRetrieverPortType {
        
        public TextFileContentRetrieverPortTypeClient() {
        }
        
        public TextFileContentRetrieverPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TextFileContentRetrieverPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextFileContentRetrieverPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextFileContentRetrieverPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AsyncAxis2Client.ServiceReference1.testResponse AsyncAxis2Client.ServiceReference1.TextFileContentRetrieverPortType.test(AsyncAxis2Client.ServiceReference1.testRequest request) {
            return base.Channel.test(request);
        }
        
        public string test() {
            AsyncAxis2Client.ServiceReference1.testRequest inValue = new AsyncAxis2Client.ServiceReference1.testRequest();
            AsyncAxis2Client.ServiceReference1.testResponse retVal = ((AsyncAxis2Client.ServiceReference1.TextFileContentRetrieverPortType)(this)).test(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsyncAxis2Client.ServiceReference1.testResponse> AsyncAxis2Client.ServiceReference1.TextFileContentRetrieverPortType.testAsync(AsyncAxis2Client.ServiceReference1.testRequest request) {
            return base.Channel.testAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsyncAxis2Client.ServiceReference1.testResponse> testAsync() {
            AsyncAxis2Client.ServiceReference1.testRequest inValue = new AsyncAxis2Client.ServiceReference1.testRequest();
            return ((AsyncAxis2Client.ServiceReference1.TextFileContentRetrieverPortType)(this)).testAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AsyncAxis2Client.ServiceReference1.retrieveTextFileContentResponse AsyncAxis2Client.ServiceReference1.TextFileContentRetrieverPortType.retrieveTextFileContent(AsyncAxis2Client.ServiceReference1.retrieveTextFileContentRequest request) {
            return base.Channel.retrieveTextFileContent(request);
        }
        
        public string retrieveTextFileContent(string path) {
            AsyncAxis2Client.ServiceReference1.retrieveTextFileContentRequest inValue = new AsyncAxis2Client.ServiceReference1.retrieveTextFileContentRequest();
            inValue.path = path;
            AsyncAxis2Client.ServiceReference1.retrieveTextFileContentResponse retVal = ((AsyncAxis2Client.ServiceReference1.TextFileContentRetrieverPortType)(this)).retrieveTextFileContent(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsyncAxis2Client.ServiceReference1.retrieveTextFileContentResponse> AsyncAxis2Client.ServiceReference1.TextFileContentRetrieverPortType.retrieveTextFileContentAsync(AsyncAxis2Client.ServiceReference1.retrieveTextFileContentRequest request) {
            return base.Channel.retrieveTextFileContentAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsyncAxis2Client.ServiceReference1.retrieveTextFileContentResponse> retrieveTextFileContentAsync(string path) {
            AsyncAxis2Client.ServiceReference1.retrieveTextFileContentRequest inValue = new AsyncAxis2Client.ServiceReference1.retrieveTextFileContentRequest();
            inValue.path = path;
            return ((AsyncAxis2Client.ServiceReference1.TextFileContentRetrieverPortType)(this)).retrieveTextFileContentAsync(inValue);
        }
    }
}
